CREATE TABLE IF NOT EXISTS intake_records (
  id VARCHAR(64) PRIMARY KEY,
  job_id VARCHAR(64),
  batch_id VARCHAR(64) NOT NULL,
  trigger_type VARCHAR(32),
  recorded_by VARCHAR(128),
  supplier VARCHAR(255),
  vegetables LONGTEXT,
  weight DECIMAL(10, 3),
  storage_date VARCHAR(32),
  captured_at TIMESTAMP NULL,
  raw_json LONGTEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
